# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - synapse-tatva-react-dev(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
        NODE_PATH: '/src'
        REACT_APP_BASE_API: 'https://synapse-tatva-api-dev.azurewebsites.net'
        REACT_APP_MSAL_CLIENT_ID: '${{ secrets.DEV_MSAL_CLIENT_ID }}'
        REACT_APP_MSAL_REDIRECT_URI: 'https://synapse-tatva-react-dev.azurewebsites.net/login'
        REACT_APP_MSAL_SCOPES: '${{ secrets.DEV_MSAL_SCOPES }}'
        REACT_APP_NAME: 'Synapse'
        
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: synapse-tatva-react-dev
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C7EE930101334EEB8DBBEB379C02B46A }}
        package: .
        
