# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - synapse-tatva-react-dev(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
       
    - name: Set up env
      uses: azure/appservice-settings@v1
      with:
        app-name: synapse-tatva-react-dev
        slot-name: Production
        app-settings-json: '${{ secrets.DEV_APP_SETTINGS }}'
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: synapse-tatva-react-dev
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C7EE930101334EEB8DBBEB379C02B46A }}
        package: .

